theme: jekyll-theme-minimal
name: Houston Apple Admins
markdown:	kramdown
title:	Houston Apple Admins
Description:	We are a group of Mac admins that gather regularly to discuss Mac management
logo:	site.png
timezone:	America/Chicago
readtime:         true
keywords:	apple, Mac, admin, Jamf, Munki, Casper, Management
twitter:	midsandhighs
facebook:	https://www.facebook.com
github:		https://github.com
